export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const SET_PROFILE_INFO = 'SET_PROFILE_INFO';
export const CHANGE_PROFILE_INFO = 'CHANGE_PROFILE_INFO';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PROFILE_FIELD = 'CHANGE_PROFILE_FIELD';