export const GET_COURSE_TASKS = 'GET_COURSE_TASKS';
export const SET_COURSE_TASKS = 'SET_COURSE_TASKS';

export const GET_COURSE_TASK = 'GET_COURSE_TASK';
export const SET_COURSE_TASK = 'SET_COURSE_TASK';

export const GET_COURSE_STATISTICS = 'GET_COURSE_STATISTICS';
export const SET_COURSE_STATISTICS = 'SET_COURSE_STATISTICS';

export const GET_COURSE_METHODICAL_MATERIALS = 'GET_COURSE_METHODICAL_MATERIALS';
export const GET_COURSE_METHODICAL_MATERIAL = 'GET_COURSE_METHODICAL_MATERIAL';
export const SET_COURSE_METHODICAL_MATERIALS = 'SET_COURSE_METHODICAL_MATERIALS';
export const SET_COURSE_METHODICAL_MATERIAL = 'SET_COURSE_METHODICAL_MATERIAL';

export const SET_COURSE_ID = 'SET_COURSE_ID';
export const SET_COURSE_ROUTE_ID = 'SET_COURSE_ROUTE_ID';
export const COMPLETE_TASK = 'COMPLETE_TASK';

export const SET_CURRENT_TASK_ERROR = 'SET_CURRENT_TASK_ERROR';
export const REMOVE_CURRENT_TASK_ERROR = 'REMOVE_CURRENT_TASK_ERROR';

export const SET_CURRENT_TASK_ERROR_TABLE_DATA = 'SET_CURRENT_TASK_ERROR_TABLE_DATA';
export const REMOVE_CURRENT_TASK_ERROR_TABLE_DATA = 'REMOVE_CURRENT_TASK_ERROR_TABLE_DATA';

export const SET_CURRENT_TASK_ANSWER = 'SET_CURRENT_TASK_ANSWER';
export const REMOVE_CURRENT_TASK_ANSWER = 'REMOVE_CURRENT_TASK_ANSWER';

export const OPEN_FINISH_COURSE_MODAL = 'OPEN_FINISH_COURSE_MODAL';
export const CLOSE_FINISH_COURSE_MODAL = 'CLOSE_FINISH_COURSE_MODAL';