export const TASKS = 'tasks';
export const CURRENT_TASK = 'current_task';
export const METHODICAL = 'methodical';
export const STATISTICS = 'statistics';

export const COURSE_ID = 'COURSE_ID';

export const GET_COURSE_TASK_FETCHING = 'GET_COURSE_TASK_FETCHING';
export const GET_COURSE_TASKS_FETCHING = 'GET_COURSE_TASKS_FETCHING';
export const GET_COURSE_METHODICAL_FETCHING = 'GET_COURSE_METHODICAL_FETCHING';
export const GET_COURSE_STATISTICS_FETCHING = 'GET_COURSE_STATISTICS_FETCHING';
export const COMPLETE_TASK_FETCHING = 'COMPLETE_TASK_FETCHING';