export const SIGN_IN_CHANGE_FIELD = 'SIGN_IN_CHANGE_FIELD';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_FETCHING = 'SIGN_IN_FETCHING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';