export const SIGN_UP_CHANGE_FIELD = 'SIGN_UP_CHANGE_FIELD';
export const SIGN_UP_PAGE_DOWN = 'SIGN_UP_PAGE_DOWN';
export const SIGN_UP_CLEAR_ALL_FIELDS = 'SIGN_UP_CLEAR_ALL_FIELDS';

export const SIGN_UP_GET_ORGANIZATIONS = 'SIGN_UP_GET_ORGANIZATIONS';
export const SIGN_UP_SET_ORGANIZATIONS = 'SIGN_UP_SET_ORGANIZATIONS';
export const SIGN_UP_GET_PERIODS = 'SIGN_UP_GET_PERIODS';
export const SIGN_UP_SET_PERIODS = 'SIGN_UP_SET_PERIODS';
export const SIGN_UP_GET_GROUPS = 'SIGN_UP_GET_GROUPS';
export const SIGN_UP_SET_GROUPS = 'SIGN_UP_SET_GROUPS';

export const SIGN_UP = 'SIGN_UP';