export const RESET_PASSWORD_CHANGE_FIELD = 'RESET_PASSWORD_CHANGE_FIELD';

export const RESET_PASSWORD = 'RESET_PASSWORD';

export const CONFIRM_NEW_PASSWORD = 'CONFIRM_NEW_PASSWORD';

export const RESET_PASSWORD_PAGE_DOWN = 'RESET_PASSWORD_PAGE_DOWN';