export const FETCHING_TRUE = 'FETCHING_TRUE';
export const FETCHING_FALSE = 'FETCHING_FALSE';
export const FETCHING_FAILED = 'FETCHING_FAILED';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';

export const GET_USER_DATA = 'GET_USER_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';

export const GET_GROUP_OPTIONS = 'GET_GROUP_OPTIONS';
export const SET_GROUP_OPTIONS = 'SET_GROUP_OPTIONS';

export const SET_AUTH_TRUE = 'SET_AUTH_TRUE';
export const SET_AUTH_FALSE = 'SET_AUTH_FALSE';